'''
Quadruple.py is a model of the quadruples that are generated by the compiler.
'''

# Path: TapiCompi.compiler.libs

class Quadruple:
    def __init__(self, operator, left, right, result):
        self.operator = operator
        self.left = left
        self.right = right
        self.result = result
        
    def get_Result(self):
        return self.result
    
    def set_Result(self, result):
        self.result = result
        
    def print(self):
        print(self.operator, self.left, self.right, self.result)
        #print(f'{self.operator:10} {self.left:10} {self.right:10} {self.result:10}')